version: '3.7'
services:
    flask:
        build: .
        command: app/app.py
        ports:
            - "8081:8081"
        volumes:
            - .:/app
        environment:
            - MEMCACHE_HOST=memcached
            - MEMCACHE_PORT=11211
        depends_on:
            - memcached
    memcached:
        image: memcached:1.6.6
        ports:
            - "11211:11211"
